name: Deploy Habbitt Website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          cd apps/frontend
          npm ci
          npm run build

      - name: Build Docker Image
        run: docker build -t habbitt/frontend:latest apps/frontend

      - name: Push Docker Image
        run: echo "Will push to local registry or future AWS ECR"
